### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by K43434** [Exitium-DEV/HD2-Cheat-Launcher#4]
After looking at the source code, I believe the issue is because my helldiver2 is not in the Steam directory, but rather stored on a different disk. Is there a way to solve this problem?

**Comment by byremo994** [comment]
`Console.WriteLine("IMPORTANT: If your Steam installation directory is not default...\nMake a file 'steam_override.txt' containing the location of your installation directory, and restart the EXE\n\nEXAMPLE: D:\\Some\\Path\\Steam\n");`

Copy paste from the readme. Just make a steam_override.txt file with the installation path.
Not sure if it'll work but who knows.
